# Generated by Django 3.2.8 on 2021-10-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'Processing'), ('DL', 'Delivering'), ('CP', 'Completed')], default='PR', max_length=50),
        ),
    ]
