# Generated by Django 3.2.8 on 2021-10-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
